from tkinter import *


def open_game_details():
    game_details_window = Toplevel()
    game_details_window.title("Game Details")
    # Game Details window
    v = IntVar()
    game_type_streetball_radiobutton = Radiobutton(game_details_window, text="Streetball", variable=v, value=1)
    game_type_basketball_radiobutton = Radiobutton(game_details_window, text="Basketball", variable=v, value=2)
    game_type_streetball_radiobutton.grid(row=0, column=0)
    game_type_basketball_radiobutton.grid(row=1, column=0)
    ### End of Game Details window
    basketball_rules_frame = LabelFrame(game_details_window, text="Basketball Rules")
    basketball_rules_frame.grid(row=2, column=0)
    basketball_number_of_periods_label = Label(basketball_rules_frame, text="Number of periods: ")
    basketball_number_of_periods_label.grid(row=0, column=0)
    #number_of_periods_input = simpledialog.askinteger("Input", "What is period length in minutes?",
    #        parent=game_details_window, minvalue=1, maxvalue=30)
    basketball_number_of_periods_input = Entry(basketball_rules_frame)
    basketball_number_of_periods_input.grid(row=0, column=1)
    basketball_periods_label = Label(basketball_rules_frame, text="Periods")
    basketball_periods_label.grid(row=1, column=0)
    basketball_period1_label = Label(basketball_rules_frame, text="1")
    basketball_period1_label.grid(row=1, column=1)
    basketball_period2_label = Label(basketball_rules_frame, text="2")
    basketball_period2_label.grid(row=1, column=2)
    basketball_period3_label = Label(basketball_rules_frame, text="3")
    basketball_period3_label.grid(row=1, column=3)
    basketball_period4_label = Label(basketball_rules_frame, text="4")
    basketball_period4_label.grid(row=1, column=4)
    basketball_period_ot_label = Label(basketball_rules_frame, text="OT")
    basketball_period_ot_label.grid(row=1, column=5)

    basketball_length_of_periods_label = Label(basketball_rules_frame, text="Length, min")
    basketball_length_of_periods_label.grid(row=2, column=0)
    basketball_period1_input = Entry(basketball_rules_frame)
    basketball_period1_input.grid(row=2, column=1)
    basketball_period2_input = Entry(basketball_rules_frame)
    basketball_period2_input.grid(row=2, column=2)
    basketball_period3_input = Entry(basketball_rules_frame)
    basketball_period3_input.grid(row=2, column=3)
    basketball_period4_input = Entry(basketball_rules_frame)
    basketball_period4_input.grid(row=2, column=4)
    basketball_period_ot_label = Entry(basketball_rules_frame)
    basketball_period_ot_label.grid(row=2, column=5)

    basketball_length_of_timeouts_label = Label(basketball_rules_frame, text="Timeout, min")
    basketball_length_of_timeouts_label.grid(row=3, column=0)
    basketball_timeout2_input = Entry(basketball_rules_frame)
    basketball_timeout2_input.grid(row=3, column=2)
    basketball_timeout3_input = Entry(basketball_rules_frame)
    basketball_timeout3_input.grid(row=3, column=3)
    basketball_timeout4_input = Entry(basketball_rules_frame)
    basketball_timeout4_input.grid(row=3, column=4)
    basketball_timeout_ot_input = Entry(basketball_rules_frame)
    basketball_timeout_ot_input.grid(row=3, column=5)

    basketball_team_fouls_label = Label(basketball_rules_frame, text="Team Fouls")
    basketball_team_fouls_label.grid(row=4, column=0)
    basketball_team_fouls1_input = Entry(basketball_rules_frame)
    basketball_team_fouls1_input.grid(row=4, column=1)
    basketball_team_fouls2_input = Entry(basketball_rules_frame)
    basketball_team_fouls2_input.grid(row=4, column=2)
    basketball_team_fouls3_input = Entry(basketball_rules_frame)
    basketball_team_fouls3_input.grid(row=4, column=3)
    basketball_team_fouls4_input = Entry(basketball_rules_frame)
    basketball_team_fouls4_input.grid(row=4, column=4)

    basketball_players_on_court_label = Label(basketball_rules_frame, text="Player on court")
    basketball_players_on_court_label.grid(row=5, column=0)
    basketball_players_on_court_input = Entry(basketball_rules_frame)
    basketball_players_on_court_input.grid(row=5, column=1)

    basketball_personal_fouls_label = Label(basketball_rules_frame, text="Personal Fouls")
    basketball_personal_fouls_label.grid(row=6, column=0)
    basketball_personal_fouls_input = Entry(basketball_rules_frame)
    basketball_personal_fouls_input.grid(row=6, column=1)


    basketball_number_of_points_label = Label(basketball_rules_frame, text="Number of points: ")
    basketball_number_of_points_label.grid(row=902, column=0)
    basketball_free_throw_points_label = Label(basketball_rules_frame, text="Free Throw")
    basketball_free_throw_points_label.grid(row=901, column=1)
    basketball_free_throw_points_input = Entry(basketball_rules_frame)
    basketball_free_throw_points_input.grid(row=902, column=1)
    basketball_game_shot_points_label = Label(basketball_rules_frame, text="Game Shot")
    basketball_game_shot_points_label.grid(row=901, column=2)
    basketball_game_shot_points_input = Entry(basketball_rules_frame)
    basketball_game_shot_points_input.grid(row=902, column=2)
    basketball_longrange_shot_points_label = Label(basketball_rules_frame, text="Long Range Shot")
    basketball_longrange_shot_points_label.grid(row=901, column=3)
    basketball_longrange_shot_points_input = Entry(basketball_rules_frame)
    basketball_longrange_shot_points_input.grid(row=902, column=3)
    #duration_of_the_period = 

    # STREETBALL SECTION
    streetball_rules_frame = LabelFrame(game_details_window, text="Streetball Rules")
    streetball_rules_frame.grid(row=3, column=0)
    streetball_number_of_periods_label = Label(streetball_rules_frame, text="Number of periods: ")
    streetball_number_of_periods_label.grid(row=0, column=0)
    #number_of_periods_input = simpledialog.askinteger("Input", "What is period length in minutes?",
    #        parent=game_details_window, minvalue=1, maxvalue=30)
    streetball_number_of_periods_input = Entry(streetball_rules_frame)
    streetball_number_of_periods_input.grid(row=0, column=1)
    streetball_periods_label = Label(streetball_rules_frame, text="Periods")
    streetball_periods_label.grid(row=1, column=0)
    streetball_period1_label = Label(streetball_rules_frame, text="1")
    streetball_period1_label.grid(row=1, column=1)
    streetball_period2_label = Label(streetball_rules_frame, text="2")
    streetball_period2_label.grid(row=1, column=2)
    streetball_period3_label = Label(streetball_rules_frame, text="3")
    streetball_period3_label.grid(row=1, column=3)
    streetball_period4_label = Label(streetball_rules_frame, text="4")
    streetball_period4_label.grid(row=1, column=4)
    streetball_period_ot_label = Label(streetball_rules_frame, text="OT")
    streetball_period_ot_label.grid(row=1, column=5)

    streetball_length_of_periods_label = Label(streetball_rules_frame, text="Length, min")
    streetball_length_of_periods_label.grid(row=2, column=0)
    streetball_period1_input = Entry(streetball_rules_frame)
    streetball_period1_input.grid(row=2, column=1)
    streetball_period2_input = Entry(streetball_rules_frame)
    streetball_period2_input.grid(row=2, column=2)
    streetball_period3_input = Entry(streetball_rules_frame)
    streetball_period3_input.grid(row=2, column=3)
    streetball_period4_input = Entry(streetball_rules_frame)
    streetball_period4_input.grid(row=2, column=4)
    streetball_period_ot_label = Entry(streetball_rules_frame)
    streetball_period_ot_label.grid(row=2, column=5)

    streetball_length_of_timeouts_label = Label(streetball_rules_frame, text="Timeout, min")
    streetball_length_of_timeouts_label.grid(row=3, column=0)
    streetball_timeout2_input = Entry(streetball_rules_frame)
    streetball_timeout2_input.grid(row=3, column=2)
    streetball_timeout3_input = Entry(streetball_rules_frame)
    streetball_timeout3_input.grid(row=3, column=3)
    streetball_timeout4_input = Entry(streetball_rules_frame)
    streetball_timeout4_input.grid(row=3, column=4)
    streetball_timeout_ot_input = Entry(streetball_rules_frame)
    streetball_timeout_ot_input.grid(row=3, column=5)

    streetball_team_fouls_label = Label(streetball_rules_frame, text="Team Fouls")
    streetball_team_fouls_label.grid(row=4, column=0)
    streetball_team_fouls1_input = Entry(streetball_rules_frame)
    streetball_team_fouls1_input.grid(row=4, column=1)
    streetball_team_fouls2_input = Entry(streetball_rules_frame)
    streetball_team_fouls2_input.grid(row=4, column=2)
    streetball_team_fouls3_input = Entry(streetball_rules_frame)
    streetball_team_fouls3_input.grid(row=4, column=3)
    streetball_team_fouls4_input = Entry(streetball_rules_frame)
    streetball_team_fouls4_input.grid(row=4, column=4)

    streetball_players_on_court_label = Label(streetball_rules_frame, text="Player on court")
    streetball_players_on_court_label.grid(row=5, column=0)
    streetball_players_on_court_input = Entry(streetball_rules_frame)
    streetball_players_on_court_input.grid(row=5, column=1)

    streetball_personal_fouls_label = Label(streetball_rules_frame, text="Personal Fouls")
    streetball_personal_fouls_label.grid(row=6, column=0)
    streetball_personal_fouls_input = Entry(streetball_rules_frame)
    streetball_personal_fouls_input.grid(row=6, column=1)

    streetball_number_of_points_label = Label(streetball_rules_frame, text="Number of points: ")
    streetball_number_of_points_label.grid(row=902, column=0)
    streetball_free_throw_points_label = Label(streetball_rules_frame, text="Free Throw")
    streetball_free_throw_points_label.grid(row=901, column=1)
    streetball_free_throw_points_input = Entry(streetball_rules_frame)
    streetball_free_throw_points_input.grid(row=902, column=1)
    streetball_game_shot_points_label = Label(streetball_rules_frame, text="Game Shot")
    streetball_game_shot_points_label.grid(row=901, column=2)
    streetball_game_shot_points_input = Entry(streetball_rules_frame)
    streetball_game_shot_points_input.grid(row=902, column=2)
    streetball_longrange_shot_points_label = Label(streetball_rules_frame, text="Long Range Shot")
    streetball_longrange_shot_points_label.grid(row=901, column=3)
    streetball_longrange_shot_points_input = Entry(streetball_rules_frame)
    streetball_longrange_shot_points_input.grid(row=902, column=3)
    #duration_of_the_period = 

